CREATE TABLE `professorSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`settingsKey` varchar(64) NOT NULL,
	`displayName` varchar(128),
	`institutionName` varchar(255),
	`sessionNameTemplate` varchar(255),
	`emailNotifications` boolean NOT NULL DEFAULT false,
	`themePref` enum('light','dark','system') NOT NULL DEFAULT 'light',
	`allowLateJoins` boolean NOT NULL DEFAULT true,
	`showResponseCountToStudents` boolean NOT NULL DEFAULT false,
	`autoAdvance` boolean NOT NULL DEFAULT false,
	`autoAdvanceTimer` int NOT NULL DEFAULT 30,
	`anonymousResponses` boolean NOT NULL DEFAULT true,
	`maxResponsesPerStudent` int NOT NULL DEFAULT 1,
	`defaultQuestionType` varchar(64) NOT NULL DEFAULT 'Short Text',
	`waitingRoomMessage` text,
	`sessionEndedMessage` text,
	`requireStudentName` boolean NOT NULL DEFAULT false,
	`showQuestionNumber` boolean NOT NULL DEFAULT true,
	`revealTotalQuestionCount` boolean NOT NULL DEFAULT true,
	`allowResponseEditing` boolean NOT NULL DEFAULT false,
	`brandingLogoUrl` text,
	`primaryAccentColor` varchar(64),
	`pollingInterval` int NOT NULL DEFAULT 2,
	`showWordCloudByDefault` boolean NOT NULL DEFAULT false,
	`showCorrectAnswerOverlay` boolean NOT NULL DEFAULT false,
	`confettiOnLaunch` boolean NOT NULL DEFAULT true,
	`csvDateFormat` enum('iso','us','eu') NOT NULL DEFAULT 'iso',
	`csvIncludeStudentId` boolean NOT NULL DEFAULT true,
	`autoDeleteAfterDays` int,
	`exportFormat` enum('csv','excel') NOT NULL DEFAULT 'csv',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `professorSettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `professorSettings_settingsKey_unique` UNIQUE(`settingsKey`)
);
